export const PRODUCTS_ACTION_TYPES = {
  PRODUCTS_REQUEST: "PRODUCTS_REQUEST",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_FAIL: "PRODUCTS_FAIL",
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",

  PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
  PRODUCT_CREATE_FAIL: "PRODUCT_CREATE_FAIL",
  PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",

  PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_FAIL: "PRODUCT_UPDATE_FAIL",
  PRODUCT_UPDATE_RESET: "PRODUCT_UPDATE_RESET",

  PRODUCT_CREATE_REVIEW_REQUEST: "PRODUCT_CREATE_REVIEW_REQUEST",
  PRODUCT_CREATE_REVIEW_SUCCESS: "PRODUCT_CREATE_REVIEW_SUCCESS",
  PRODUCT_CREATE_REVIEW_FAIL: "PRODUCT_CREATE_REVIEW_FAIL",
  PRODUCT_CREATE_REVIEW_RESET: "PRODUCT_CREATE_REVIEW_RESET",

  PRODUCT_TOP_REQUEST: "PRODUCT_TOP_REQUEST",
  PRODUCT_TOP_SUCCESS: "PRODUCT_TOP_SUCCESS",
  PRODUCT_TOP_FAIL: "PRODUCT_TOP_FAIL",
};
